[toolchain]
# When channel changes, update the sha256 in flake.nix too.
# Using a nightly channel to access extra rustfmt features.
channel = "nightly-2026-08-20"
components = ["rust-analyzer", "clippy", "rustfmt"]
profile = "minimal"
