#!/bin/sh
set -eu

# Use git-upload-pack-slow.py to simulate patchy connections during git fetch.
# Only do so when fetching from subx.
export PATH=$OLD_PATH
if test "$#" -gt 10 && test "$1" = "-C" && test "$3" = "fetch" && test "${10-}" = "--negotiation-tip=refs/namespaces/subx/*"; then
    script_dir=$(dirname "$0")
    working_dir="$2"
    shift 3
    upload_pack_script=$(cat <<EOF
sh -c 'git upload-pack "\$0" "\$@" | python3 -u "$script_dir/git-upload-pack-slow.py"'
EOF
)
    exec git -C "$working_dir" fetch --upload-pack "$upload_pack_script" "$@"
fi
exec git "$@"
