#!/bin/sh
set -eu

containsElement() {
    local needle="$1"
    shift
    local element
    for element; do
        if [ "$element" = "$needle" ]; then
            return 0
        fi
    done
    return 1
}

# Use git-upload-pack-slow.py to simulate patchy connections during git fetch.
# Only do so when fetching from subx.
export PATH=$OLD_PATH
if test "$1" = "-C" && test "$3" = "fetch" && containsElement '--negotiation-tip=refs/namespaces/namex/*' "$@"; then
    script_dir=$(dirname "$0")
    working_dir="$2"
    shift 3
    upload_pack_script=$(cat <<EOF
sh -c 'git upload-pack "\$0" "\$@" | python3 -u "$script_dir/git-upload-pack-slow.py"'
EOF
)
    exec git -C "$working_dir" fetch --upload-pack "$upload_pack_script" "$@"
fi
exec git "$@"
